const char AIS_INDEX[] PROGMEM =
  "<body>"
  "<center>"
  "<div class=\"card\" style=\"width: 100%%;max-width: 600px;\">"
  "<img class=\"card-img-top\" src=\"https://raw.githubusercontent.com/sviete/Tasmota-ESP32/development/ais_files/ais-smart-home.jpeg\" alt=\"Card image cap\">"
  "<div class=\"card-img-overlay\">"
  "<h5 class=\"card-title\" style=\"text-align:left;color:black\"><span class=\"mdi mdi-thermometer\"> %s °C</h5>"
  "</div>"

  "<div class=\"card-body\" style=\"margin-top:2em;\">"
  "<div class=\"row row-cols-2 row-cols-md-2 g-4\">"
  "<div class=\"col\">"
  "<div class=\"card\">"
  "<a href=\"ah?\" style=\"color:#18bbf2\">"
  "<span class=\"mdi mdi-home-assistant\" style=\"font-size: 4em;\"></span>"
  "<div class=\"card-body\">"
  "<h5 class=\"card-title\">Home Assistant</h5>"
  "</div>"
  "</a>"
  "</div>"
  "</div>"
  "<div class=\"col\">"
  "<div class=\"card\">"
  "<a href=\"az?\" style=\"color:#EC0B43\">"
  "<span class=\"mdi mdi-zigbee\"style=\"font-size: 4em;\"></span>"
  "<div class=\"card-body\">"
  "<h5 class=\"card-title\">Zigbee2Mqtt</h5>"
  "</div>"
  "</a>"
  "</div>"
  "</div>"
  "<div class=\"col\">"
  "<div class=\"card\">"
  "<a href=\"ble?\" style=\"color:#3f51b5\">"
  "<span class=\"mdi mdi-bluetooth\" style=\"font-size: 4em;\"></span>"
  "<div class=\"card-body\">"
  "<h5 class=\"card-title\">Bluetooth</h5>"
  "</div>"
  "</a>"
  "</div>"
  "</div>"
  "<div class=\"col\">"
  "<div class=\"card\">"
  "<a href=\"am?\" style=\"color:#ff9800\">"
  "<span class=\"mdi mdi-message-text-outline\" style=\"font-size: 4em;\"></span>"
  "<div class=\"card-body\">"
  "<h5 class=\"card-title\">MQTT</h5>"
  "</div>"
  "</a>"
  "</div>"
  "</div>"

  "<div class=\"col\">"
  "<div class=\"card\">"
  "<a href=\"a1?\" style=\"color:#5b0566\">"
  "<span class=\"mdi mdi-update\" style=\"font-size: 4em;\"></span>"
  "<div class=\"card-body\">"
  "<h5 class=\"card-title\">Upgrade</h5>"
  "</div>"
  "</a>"
  "</div>"
  "</div>"

  "<div class=\"col\">"
  "<div class=\"card\">"
  "<a href=\"at?\" style=\"color:#000000\">"
  "<span class=\"mdi mdi-console\" style=\"font-size: 4em;\"></span>"
  "<div class=\"card-body\">"
  "<h5 class=\"card-title\">Terminal</h5>"
  "</div>"
  "</a>"
  "</div>"
  "</div>"
  "</div>"
  "</div>"

  "<div style=\"text-align: right; margin-right: 2em; z-index: 999999;\">"
  "<a href=\"ai?\" style=\"color: black;text-decoration: none;\">"
  "<span class=\"mdi mdi-memory\" style=\"font-size: 2em;\"></span>" 
  "<span style=\"line-height: 2em; vertical-align: super;\">AIS version %s <a href=\"cn?\" style=\"color:black;text-decoration:none;\">&nbsp;&nbsp;.</a></span>"
  "</a>"
  "</div>"
  
;
