const char AIS_ABOUT[] PROGMEM =
"<body>"
"<center>"
"<div class=\"card\" style=\"width:100%%;max-width:600px;margin-top:2em;background-color:#1f272b\">"
"  <div class=\"container-fluid\">"
"    <div class=\"row\">"
"      <h2><strong style=\"color:red;\">AIS</strong> adapter <strong style=\"color:red;\">1</strong></h2>"
"      <p><strong>Program Version:</strong> %s <br/>"
"        <strong>Build Date & Time:</strong> %s<br/>"
"        <strong>Core/SDK Version:</strong> %s<br/>"
"        <strong>ESP Chip Id:</strong> %d (%s)</p>"
"      <div class=\"align-self-center\">"
"        <img src=\"https://raw.githubusercontent.com/sviete/Tasmota-ESP32/development/ais_files/about.webp\" style=\"width: 90%%;\"></img>"
"      </div>"
"        <br/>"
"        <h4>Developed by</h4>"
"        <p><a href=\"www.ai-speaker.com\" style=\"color: white;text-decoration:none\">AI-Speaker.com</a><br/>"
"        <a href=\"mailto:info@ai-speaker.com\" style=\"color:white;text-decoration:none\">info@ai-speaker.com</a><br/>"
"        <a href=\"https://github.com/sviete\" style=\"color:white;text-decoration:none\">github.com/sviete</a></p>"
"    </div>"
"  </div>"
"<button onclick=\"window.location.href='/'\" type=\"button\" class=\"btn btn-primary btn-lg\" style=\"width: 100%;\">Main Menu</button>"
"</div>"
;
