const char AIS_MQTT[] PROGMEM =
"<body >"
"<center>"  
"  <div class=\"card\" style=\"width: 100%%;max-width: 600px;margin-top: 2em;\">"
"  <h2 style=\"margin-top: 1em;\">MQTT parameters</h2>"
"  <form style=\"text-align: left;padding: 2em;\" method=\"get\" action=\"am\">"
"    <div class=\"mb-3\">"
"      <label for=\"mh\" class=\"form-label\">MQTT host</label>"
"      <input type=\"text\" class=\"form-control\" placeholder=\"MQTT host IP\" id=\"mh\" value=\"%s\" name=\"mh\">"
"    </div>"
"    <div class=\"mb-3\">"
"      <label for=\"ml\" class=\"form-label\">MQTT port</label>"
"      <input type=\"number\" class=\"form-control\" id=\"ml\" placeholder=\"1883\" value=\"%d\" name=\"ml\">"
"    </div>"
"    <div class=\"mb-3\">"
"      <label for=\"mu\" class=\"form-label\">MQTT User</label>"
"      <input type=\"text\" class=\"form-control\" id=\"mu\" placeholder=\"MQTT user\" value=\"%s\" name=\"mu\">"
"    </div>"
"    <div class=\"mb-3\">"
"      <label for=\"mp\" class=\"form-label\">MQTT Password</label>"
"      <input type=\"password\" class=\"form-control\" id=\"mp\" placeholder=\"Password\" value=\"****\" name=\"mp\">"
"    </div>"
"    <div class=\"input-group input-group-sm mb-3\">"
"      <span class=\"input-group-text\" id=\"mc-sm\">MQTT Client</span>"
"      <input id=\"mc\" value=\"%s\" name=\"mc\" type=\"text\" class=\"form-control\">"
"    </div>"
"    <div class=\"input-group input-group-sm mb-3\">"
"      <span class=\"input-group-text\" id=\"inputGroup-sizing-sm\">MQTT topic</span>"
"      <input id=\"mt\" value=\"%s\" name=\"mt\" type=\"text\" class=\"form-control\">"
"    </div>"
"    <div class=\"input-group input-group-sm mb-3\">"
"      <span class=\"input-group-text\" id=\"inputGroup-sizing-sm\">MQTT Full Topic</span>"
"      <input id=\"mf\" value=\"%s\" name=\"mf\" type=\"text\" class=\"form-control\">"
"    </div>"
"      <button class=\"btn btn-lg  btn-primary\" name=\"save\" type=\"submit\" class=\"button bgrn\" style=\"width: 100%%;\">Save</button>"
"      <br/><br/><button onclick=\"window.location.href='/'\" type=\"button\" class=\"btn btn-primary btn-lg\" style=\"width: 100%%;\">Main Menu</button>"
"  </form>"    
;
