const char AIS_INFO[] PROGMEM =
"<script>setTimeout(function(){location.href='.';},%d);</script>"
"<style>"
"  body {"
"  background-color: #272727;"
"  padding: 10px;"
" }"
".container-fluid {"
"    padding: 60px 50px;"
"  }"
"  .bg-grey {"
"    background-color: #f6f6f6;"
"  }"
"  .logo {"
"    font-size: 200px;"
"  }"
"  @media screen and (max-width: 768px) {"
"    .col-sm-4 {"
"      text-align: center;"
"      margin: 25px 0;"
"    }"
"  }"
"</style>"
"<body >"
"<center>"
"<div class=\"card\" style=\"width:100%;max-width:600px;margin-top:2em;\">"
"  <div class=\"container-fluid bg-grey\">"
"    <div class=\"row\">"
"      <div class=\"col-sm-8\">"
"        <h1><strong></strong>AIS adapter</strong></h1>"
"        <br/>"
"        <button class=\"btn btn-primary btn-success\" type=\"button\" onclick=\"window.location.href='/'\">"
"          <span class=\"spinner-grow spinner-grow-sm\" role=\"status\" aria-hidden=\"true\"></span>"
"          Loading Menu..."
"        </button>"
"      </div>"
"      <div class=\"col-sm-4 align-self-center\">"
"        <span class=\"mdi mdi-content-save\" style=\"font-size: 6em;\"></span>"
"      </div>"
"    </div>"
"  </div>"
"</div>"
"</center>"
;
