const char AIS_Z2M[] PROGMEM =
"<body >"
"<center>"  
"  <div class=\"card\" style=\"width: 100%%;max-width: 600px;margin-top: 2em;\">"
"    <div class=\"card-body\">"
"    <img src=\"https://raw.githubusercontent.com/sviete/Tasmota-ESP32/development/ais_files/z2m_logo.png\" style=\"width: 7em; margin: 1em;\"></img>"
"      <h5 class=\"card-title\">Connecting to Zigbee2MQTT      </h5>"
"      <p class=\"card-text\">This assumes you already have a basic knowledge of installing custom addons in HA and have an MQTT broker already configured within Home Assistant.</p>"
"    </div>"
"    <ul class=\"list-group list-group-flush\" style=\"text-align: left;\">"
"      <li class=\"list-group-item\">1. Install Zigbee2MQTT Add On by adding the custom github repository.</li>"
"      <li class=\"list-group-item\">2. Add the following line to the Configuration > Options > Serial text field. <code>port: tcp://%s:8888"
"      </code></li>"
"      <li class=\"list-group-item\">3.... </li>"
"    </ul>"
"    <div class=\"card-body\">"
"      <a href=\"https://ai-speaker.com/docs/ais_zigbee_index\" class=\"card-link\"><span class=\"mdi mdi-web-box\"></span>Documentation</a>"
"      <a href=\"https://github.com/sviete/Tasmota-ESP32\" class=\"card-link\"><span class=\"mdi mdi-github\"></span>Source code</a>"
"      <br/><br/><button onclick=\"window.location.href='/'\" type=\"button\" class=\"btn btn-primary btn-lg\" style=\"width: 100%%;\">Main Menu</button>"
"    </div>"
;