const char AIS_MQTT[] PROGMEM =
"<script>var x=null,lt,to,tp,pc='';eb=s=>document.getElementById(s);qs=s=>document.querySelector(s);sp=i=>eb(i).type=(eb(i).type==='text'?'password':'text');wl=f=>window.addEventListener('load',f);function jd(){var t=0,i=document.querySelectorAll('input,button,textarea,select');while(i.length>=t){if(i[t]){i[t]['name']=(i[t].hasAttribute('id')&&(!i[t].hasAttribute('name')))?i[t]['id']:i[t]['name'];}t++;}}function sf(s){var t=0,i=document.querySelectorAll('.hf');while(i.length>=t){if(i[t]){i[t].style.display=s?'block':'none';}t++;}}wl(jd);</script>"
"<style>"
"  body {"
"  background-color: #272727;"
"  padding: 10px;"
" }"
"button.btn-back {"
"  margin-left:1em;"
"  border-radius: 50%% !important;"
"  background-color: rgba(255, 255, 255, 0.08);"
"  color: white;"
"  border: none !important;"
"  -webkit-transition: background-color 1s, color 1s, -webkit-transform 0.5s;"
"  transition: background-color 1s, transform 0.5s;"
"}"
"button.btn-back:hover {"
"  background-color: rgba(255, 255, 255, 0.4);"
"  color: black;"
"  -webkit-transform: translateX(-5px);"
"  -webkit-box-shadow: 5px 0px 18px 0px rgba(105,105,105,0.8);"
"  -moz-box-shadow: 5px 0px 18px 0px rgba(105,105,105,0.8);"
"  box-shadow: 5px 0px 18px 0px rgba(105,105,105,0.8);"
"}"
"</style>"
"<body >"
"<button onclick=\"window.location.href='/'\" class=\"btn-back btn btn-lg text-center\"><span class=\"mdi mdi-arrow-left\" style=\"font-size: large;\"></span></button>"
"<center>"
"<div class=\"card\" style=\"width: 100%;max-width: 800px;margin-top: 2em;\">"
"  <h2 style=\"margin-top: 1em;\">MQTT parameters</h2>"
"  <form style=\"text-align: left;padding: 2em;\" method=\"get\" action=\"am\">"
"    <div class=\"mb-3\">"
"      <label for=\"mh\" class=\"form-label\">MQTT host</label>"
"      <input type=\"text\" class=\"form-control\" placeholder=\"MQTT host IP\" id=\"mh\" value=\"%s\" name=\"mh\">"
"    </div>"
"    <div class=\"mb-3\">"
"      <label for=\"ml\" class=\"form-label\">MQTT port</label>"
"      <input type=\"number\" class=\"form-control\" id=\"ml\" placeholder=\"1883\" value=\"%d\" name=\"ml\">"
"    </div>"
"    <div class=\"mb-3\">"
"      <label for=\"mu\" class=\"form-label\">MQTT User</label>"
"      <input type=\"text\" class=\"form-control\" id=\"mu\" placeholder=\"MQTT user\" value=\"%s\" name=\"mu\">"
"    </div>"
"    <div class=\"mb-3\">"
"      <label for=\"mp\" class=\"form-label\">MQTT Password</label>"
"      <input type=\"password\" class=\"form-control\" id=\"mp\" placeholder=\"Password\" value=\"****\" name=\"mp\">"
"    </div>"
"    <div class=\"input-group input-group-sm mb-3\">"
"      <span class=\"input-group-text\" id=\"mc-sm\">MQTT Client</span>"
"      <input id=\"mc\" value=\"%s\" name=\"mc\" type=\"text\" class=\"form-control\">"
"    </div>"
"    <div class=\"input-group input-group-sm mb-3\">"
"      <span class=\"input-group-text\" id=\"inputGroup-sizing-sm\">MQTT topic</span>"
"      <input id=\"mt\" value=\"%s\" name=\"mt\" type=\"text\" class=\"form-control\">"
"    </div>"
"    <div class=\"input-group input-group-sm mb-3\">"
"      <span class=\"input-group-text\" id=\"inputGroup-sizing-sm\">MQTT Full Topic</span>"
"      <input id=\"mf\" value=\"%s\" name=\"mf\" type=\"text\" class=\"form-control\">"
"    </div>"
"    <div class=\"d-grid gap-2 d-md-flex justify-content-md-end\">"
"      <button class=\"btn btn-lg  btn-primary\" name=\"save\" type=\"submit\" class=\"button bgrn\">Save</button>"
"    </div>"
"  </form>"    
"</div>"
"</center>"
;
