const char AIS_Z2M[] PROGMEM =
"<style>"
"    body {"
"  background-color: #272727;"
"  padding: 10px;"
"}"
"button.btn-back {"
"  margin-left:1em;"
"  border-radius: 50%% !important;"
"  background-color: rgba(255, 255, 255, 0.08);"
"  color: white;"
"  border: none !important;"
"  -webkit-transition: background-color 1s, color 1s, -webkit-transform 0.5s;"
"  transition: background-color 1s, transform 0.5s;"
"}"
"button.btn:btn-back {"
"  background-color: rgba(255, 255, 255, 0.4);"
"  color: black;"
"  -webkit-transform: translateX(-5px);"
"  -webkit-box-shadow: 5px 0px 18px 0px rgba(105,105,105,0.8);"
"  -moz-box-shadow: 5px 0px 18px 0px rgba(105,105,105,0.8);"
"  box-shadow: 5px 0px 18px 0px rgba(105,105,105,0.8);"
"}"
"</style>"
"<body >"
"<button onclick=\"window.location.href='/'\" class=\"btn btn-back btn-lg text-center\"><span><span class=\"mdi mdi-arrow-left\" style=\"font-size: large;\"></span></span></button>"
"<center>"  
"  <div class=\"card\" style=\"width: 100%;max-width: 600px;margin-top: 2em;\">"
"    <span class=\"mdi mdi-zigbee\" style=\"font-size: 7em; color: #EC0B43;\"></span>"
"    <div class=\"card-body\">"
"      <h5 class=\"card-title\">Connecting to Zigbee2MQTT      </h5>"
"      <p class=\"card-text\">This assumes you already have a basic knowledge of installing custom addons in HA and have an MQTT broker already configured within Home Assistant.</p>"
"    </div>"
"    <ul class=\"list-group list-group-flush\" style=\"text-align: left;\">"
"      <li class=\"list-group-item\">1. Install Zigbee2MQTT Add On by adding the custom github repository.</li>"
"      <li class=\"list-group-item\">2. Add the following line to the Configuration > Options > Serial text field. <code>port: tcp://%s:8888"
"      </code></li>"
"      <li class=\"list-group-item\">3.... </li>"
"    </ul>"
"    <div class=\"card-body\">"
"      <a href=\"https://ai-speaker.com/docs/ais_zigbee_index\" class=\"card-link\"><span class=\"mdi mdi-web-box\"></span>Documentation</a>"
"      <a href=\"https://github.com/sviete/Tasmota-ESP32\" class=\"card-link\"><span class=\"mdi mdi-github\"></span>Source code</a>"
"    </div>"
"  </div>"
"</center>"
;