const char AIS_HA[] PROGMEM =
"<body >"
"<center>"  
"  <div class=\"card\" style=\"width: 100%%;max-width: 600px;margin-top: 2em;\">"
"    <div class=\"card-body\">"
"    <img src=\"https://raw.githubusercontent.com/sviete/Tasmota-ESP32/development/ais_files/ha_logo.png\" style=\"width: 7em; margin: 1em;\"></img>"
"      <h5 class=\"card-title\">Connecting to Home Assistant with ZHA</h5>"
"      <p class=\"card-text\">In Home Assistant (requires version 0.113+) go to <b>Configuration</b> - <b>Integrations</b>, click the <b>+</b> icon, search for <b>ZHA</b> integration and select it.</p>"
"    </div>"
"    <ul class=\"list-group list-group-flush\" style=\"text-align: left;\">"
"      <li class=\"list-group-item\">1. For Radio Type choose <b>“EZSP”</b></li>"
"      <li class=\"list-group-item\">2. Choose <b>“software”</b> for ‘data flow control’</li>"
"      <li class=\"list-group-item\">3. Under <b>“Serial device path”</b> enter <code>socket://%s:8888</code> </li>"
"      <li class=\"list-group-item\">3. When the ais adapter is discovered you will get a confirmation message </li>"
"    </ul>"
"    <div class=\"card-body\">"
"      <a href=\"https://ai-speaker.com/docs/ais_zigbee_index\" class=\"card-link\"><span class=\"mdi mdi-web-box\"></span>Documentation</a>"
"      <a href=\"https://github.com/sviete/Tasmota-ESP32\" class=\"card-link\"><span class=\"mdi mdi-github\"></span>Source code</a>"
"      <br/><br/><button onclick=\"window.location.href='/'\" type=\"button\" class=\"btn btn-primary btn-lg\" style=\"width: 100%%;\">Main Menu</button>"
"    </div>"
;
