const char AIS_INFO[] PROGMEM =
"<script>setTimeout(function(){location.href='.';},%d);</script>"
"<style>"
".container-fluid {"
"    padding: 60px 50px;"
"  }"
"  .bg-grey {"
"    background-color: #f6f6f6;"
"  }"
"  .logo {"
"    font-size: 200px;"
"  }"
"  @media screen and (max-width: 768px) {"
"    .col-sm-4 {"
"      text-align: center;"
"      margin: 25px 0;"
"    }"
"  }"
"</style>"
"<body >"
"<center>"
"<div class=\"card\" style=\"width:100%;max-width:600px;margin-top: 2em;\">"
"  <div class=\"container-fluid bg-grey\">"
"    <div class=\"row\">"
"      <div class=\"alert alert-success\" role=\"alert\">"
"        <span class=\"mdi mdi-content-save\" style=\"font-size: 1em;\"></span> &nbsp;Save Success!"
"      </div>"
"      <span class=\"mdi mdi-memory\" style=\"font-size:7em;\"></span>"
"      <br/><br/><br/><br/><br/><br/><br/><br/>"
"      <span>"
"      <span class=\"spinner-grow spinner-grow-sm\" role=\"status\" aria-hidden=\"true\"></span>"
"      Restarting and Loading Menu..."
"      </span>"
"      <br/><br/>"
"      <button onclick=\"window.location.href='/'\" type=\"button\" class=\"btn btn-primary btn-lg\" style=\"width:100%;\">Main Menu</button>"
"    </div>"
"  </div>"
;
