const char AIS_BT[] PROGMEM =
"<style>div.form-check input.big-check-input{width:4em;height:2em;}</style>"
"<body >"
"<center>"
"<div class=\"card\" style=\"width: 100%;max-width: 600px;margin-top: 2em;\">"
"  <h2 style=\"margin-top: 1em;'\">Bluetooth settings</h2>"
"    <center>"
"    <img src=\"https://raw.githubusercontent.com/sviete/Tasmota-ESP32/development/ais_files/ble_logo_org.png\" style=\"width: 7em; margin: 1em;\"></img>"
"    </center>"
"  <form style=\"text-align: left;padding: 2em;\" method=\"get\" action=\"abl\">"
"    <div class=\"form-check form-switch\">"
"      <input id=\"e0\" name=\"e0\" class=\"big-check-input form-check-input\" type=\"checkbox\" %s>"
"      <label class=\"form-check-label\" for=\"e0\" style=\"line-height: 2.5em;\">&nbsp;Enable bloototh</label>"
"    </div>"  
"    <br/>"
"    <div class=\"form-check form-switch\">"
"      <input id=\"e1\" name=\"e1\" class=\"big-check-input form-check-input\" type=\"checkbox\" %s >"
"      <label class=\"form-check-label\" for=\"e1\" style=\"line-height: 2.5em;\">&nbsp;Enable active scan (not stored in config)</label>"
"    </div>"  
"    <br/><br/>"
"    <button class=\"btn btn-lg btn-primary\" name=\"save\" type=\"submit\" class=\"button bgrn\"  style=\"width: 100%%;\">Save</button>"  
"    <br/><br/>"
;
